'use client';
import {localizeTownUI} from '@/lib/town/ui-i18n';
import type {Locale} from '@/lib/community/i18n';
import {Gift,Wind,DoorOpen,Flower2,Heart,Volume2,VolumeX,ArrowUp,ArrowDown,Clock3,MoveUpRight} from 'lucide-react';
import type {TownEngine,TownState} from '@/lib/town/engine';
import {INITIAL_ADVENTURE,TIME_TRIPS} from '@/lib/town/adventure';
import {INITIAL_WEATHER,SEASONS,type Season} from '@/lib/town/weather';
import {INITIAL_AUDIO} from '@/lib/town/sound';
import {ACTORS,PLACES,type PlaceId} from '@/lib/town/world';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function Pocket({open,onClose,s,engine,locale='zh-CN'}:{locale?:Locale;open:boolean;onClose:()=>void;s:TownState;engine:TownEngine|null}){
 const a=s.adventure??INITIAL_ADVENTURE;
 return localizeTownUI(<Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent closeLabel="关闭" className="pocket-dialog"><DialogHeader><span className="eyebrow">A POCKET FULL OF WONDERS</span><DialogTitle>今天的小冒险</DialogTitle><DialogDescription>找哆啦A梦领取道具，再到空地和伙伴玩一会儿。</DialogDescription></DialogHeader>
 <div className="pocket-grid"><section className="gadget-card"><Wind/><h3>竹蜻蜓</h3><p>飞过屋顶，从空中看看熟悉的街区。</p><button className="primary-action" disabled={!a.inventory.includes('bamboo')} onClick={()=>{engine?.adventure.fly();onClose();}}>{a.inventory.includes('bamboo')?(a.flying?'安全着陆':'戴上，起飞'):'和哆啦A梦聊聊解锁'}<MoveUpRight size={16}/></button></section>
 <section className="gadget-card"><DoorOpen/><h3>任意门</h3><p>打开一扇门，让想去的地方就在眼前。</p><label className="field-label">门的另一边<select aria-label="任意门目的地" value={a.portalTarget} onChange={e=>{if(engine){engine.adventure.state.portalTarget=e.target.value as PlaceId;engine.emit();}}}>{PLACES.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button className="primary-action" disabled={!a.inventory.includes('door')} onClick={()=>{engine?.adventure.openPortal(a.portalTarget);onClose();}}>{a.inventory.includes('door')?'打开任意门':'等待领取道具'}</button></section></div>
 <div className="pocket-note"><Clock3 size={21}/><div><b>书桌里的时光机</b><p>去二楼书桌前，按 E 拉开浅抽屉，再进入时光机。</p></div><button onClick={()=>{engine?.teleport('bedroom');onClose();}}>去二楼 ↗</button></div>
 <div className="pocket-note"><Flower2 size={21}/><div><b>小花 × {a.flowers}　·　静香好感 {'♥'.repeat(a.friendship)}{'♡'.repeat(5-a.friendship)}</b><p>在家门口或静香家的花园取花，送给她、聊聊天，再约她散步。</p></div><button onClick={()=>{engine?.adventure.collectFlower();onClose();}}>取一朵花</button></div>
 <div className="meet-neighbors">{ACTORS.filter(v=>['doraemon','shizuka','gian','suneo'].includes(v.id)).map(v=><button key={v.id} onClick={()=>{engine?.meetActor(v.id);onClose();}}>找{v.name} ↗</button>)}</div><p className="pocket-hint">空地里的胖虎和小夫有棒球练习和投球对决。最好成绩：{a.best} 次命中。</p>
 </DialogContent></Dialog>,locale);
}
export function TalkActions({s,engine,locale='zh-CN'}:{locale?:Locale;s:TownState;engine:TownEngine|null}){const id=s.actor?.id;return localizeTownUI(<div className="talk-actions">{id==='doraemon'&&<button onClick={()=>engine?.adventure.getGift()}><Gift size={17}/>借我两件秘密道具</button>}{id==='shizuka'&&<><button onClick={()=>engine?.adventure.friend('talk')}><Heart size={16}/>分享今天的趣事</button><button onClick={()=>engine?.adventure.friend('flower')}><Flower2 size={16}/>送她一朵花</button><button onClick={()=>engine?.adventure.friend('walk')}>约她一起散步 ↗</button></>}{(id==='gian'||id==='suneo')&&<><button onClick={()=>engine?.adventure.startGame('baseball')}>⚾ 一起练习挥棒</button><button onClick={()=>engine?.adventure.startGame('dodge')}>⚾ 来一场投球对决</button></>}</div>,locale);}
export function AdventureHUD({s,engine,locale='zh-CN'}:{locale?:Locale;s:TownState;engine:TownEngine|null}){const a=s.adventure??INITIAL_ADVENTURE,au=s.audio??INITIAL_AUDIO;return localizeTownUI(<>
 <button className="sound-toggle" aria-label={au.enabled?'关闭音乐与环境音':'开启音乐与环境音'} onClick={()=>{void engine?.sound.enable(!au.enabled).then(()=>engine?.emit());}}>{au.enabled?<Volume2 size={18}/>:<VolumeX size={18}/>}<span>{au.enabled?'小镇的声音':'开启声音'}</span></button>
 {a.message&&<div className="adventure-toast" role="status">{a.message}</div>}
 {a.flying&&<div className="flight-controls"><Wind size={18}/><b>离地 {a.altitude.toFixed(1)} m</b><button aria-label="向上飞" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);engine?.keys.add('Space');}} onPointerUp={()=>engine?.keys.delete('Space')} onPointerCancel={()=>engine?.keys.delete('Space')}><ArrowUp size={18}/></button><button aria-label="向下飞" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);engine?.keys.add('ControlLeft');}} onPointerUp={()=>engine?.keys.delete('ControlLeft')} onPointerCancel={()=>engine?.keys.delete('ControlLeft')}><ArrowDown size={18}/></button><button onClick={()=>engine?.adventure.land()}>着陆 · C</button></div>}
 {a.portal&&<div className="activity-hud"><DoorOpen/><h3>门的那边是<br/>{PLACES.find(p=>p.id===a.portalTarget)?.title}</h3><p>走到门前，跨进这一次冒险。</p><button className="primary-action" onClick={()=>engine?.adventure.enterPortal()}>穿过任意门 ↗</button></div>}
 {a.activity!=='none'&&a.activity!=='time'&&<div className="activity-hud"><span className="eyebrow">AFTER SCHOOL CLUB</span><h3>{a.activity==='walk'?'和静香一起散步':a.activity==='baseball'?'棒球练习':'空地投球对决'}</h3><p>{a.activity==='walk'?'♥ 一起走一段放学路':a.activity==='baseball'?`第 ${Math.min(5,a.round)} / 5 球 · 命中 ${a.score}`:`还剩 ${Math.ceil(a.remaining)} 秒 · 命中 ${a.score}`}</p><strong className="game-cue">{a.cue||'准备好了吗？'}</strong>{a.activity!=='walk'&&<><button className="primary-action" onClick={()=>engine?.adventure.action()}>{a.activity==='baseball'?'挥棒':'投球'} · 空格</button><p className="game-instructions">{a.activity==='baseball'?'等球靠近身体再挥棒，击中时球会飞回空地。':'WASD 左右闪避来球，按空格向伙伴投球。'}</p></>}<button className="text-action" onClick={()=>engine?.adventure.stopActivity()}>结束活动</button></div>}
 {s.house==='home'&&s.floor===1&&!s.actor&&a.activity==='none'&&<button className="drawer-action" onClick={()=>a.drawer?engine?.adventure.enterTime():engine?.adventure.openDrawer()}><Clock3 size={17}/>{a.drawer?'进入抽屉时光机':'打开书桌抽屉'}</button>}
 {a.activity==='time'&&<div className="time-menu"><span className="eyebrow">THE TIME MACHINE</span><h2>{a.travel?'穿过时间的隧道…':'下一站，哪个季节？'}</h2><p>坐在抽屉后的时光机上，去另一个季节的小镇。</p><div>{TIME_TRIPS.map(t=><button disabled={a.travel} key={t.id} onClick={()=>engine?.adventure.travel(t.id)}>{t.title}<span>↗</span></button>)}</div><button className="text-action" onClick={()=>engine?.adventure.leaveTime()}>回到房间</button></div>}
 </>,locale);}
export function WorldSettings({s,engine,locale='zh-CN'}:{locale?:Locale;s:TownState;engine:TownEngine|null}){const w=s.weather??INITIAL_WEATHER,au=s.audio??INITIAL_AUDIO;return localizeTownUI(<div className="world-settings"><label className="field-label">四季<div className="season-choices">{SEASONS.map(v=><button key={v.id} className={v.id===w.season?'selected':''} onClick={()=>{engine?.weather.setSeason(v.id as Season);engine?.emit();}}><b>{v.name}</b><span>{v.detail}</span></button>)}</div></label><label className="field-label">小镇时间 · 第 {w.day} 天 · {w.time}<input type="range" min="0" max="23.99" step=".25" value={w.hour} aria-label="小镇时间" onChange={e=>{engine?.weather.setHour(Number(e.target.value));engine?.emit();}}/></label><label className="check-setting"><input type="checkbox" checked={w.auto} onChange={e=>{if(engine){engine.weather.state.auto=e.target.checked;engine.emit();}}}/>让时间自然流逝，四天后换季</label>
 <div className="setting-row"><div><b>音乐与环境音</b><p>{au.track}</p></div><button className="audio-switch" onClick={()=>{void engine?.sound.enable(!au.enabled).then(()=>engine?.emit());}}>{au.enabled?'关闭':'开启'}</button></div>
 {(['music','ambience'] as const).map(k=><label className="field-label" key={k}>{k==='music'?'背景音乐':'风、鸟鸣与虫鸣'}<input type="range" min="0" max="1" step=".01" value={au[k]} aria-label={k==='music'?'背景音乐音量':'环境音量'} onChange={e=>{engine?.sound.volume(k,Number(e.target.value));engine?.emit();}}/></label>)}
 <label className="music-import">导入哆啦A梦 BGM 或自己的音乐<input type="file" accept="audio/*" onChange={e=>{const f=e.target.files?.[0];if(f){engine?.sound.importMusic(f);engine?.emit();}}}/></label><p className="setting-caption">默认播放原创童趣配乐。导入的音乐仅在本机播放。</p>{au.error&&<p role="alert">{au.error}</p>}
 </div>,locale);}
