const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
global.document={documentElement:{dataset:{assetBase:'/frank_worlds/'}},hidden:false};
global.window={};
const {TownEngine}=require('../lib/town/engine.ts');
const e=Object.create(TownEngine.prototype),handlers=new Map(),canvas={focus(){},setPointerCapture(){},hasPointerCapture(){return true},releasePointerCapture(){}};
Object.assign(e,{renderer:{domElement:canvas},state:{ready:true,mode:'first'},pointer:{down:false,id:-1,x:0,y:0,moved:0},paused:false,keys:new Set(),touch:{x:0,y:0},touchRunning:false,yaw:0,pitch:0,azimuth:0,on(target,type,fn){handlers.set((target===canvas?'canvas:':target===window?'window:':'document:')+type,fn);}});
e.bind();const event=(id,x,y)=>({pointerId:id,clientX:x,clientY:y});
e.setTouch(.8,-.6);e.setTouchRun(true);
handlers.get('canvas:pointerdown')(event(2,100,100));handlers.get('canvas:pointerdown')(event(3,0,0));assert.equal(e.pointer.id,2);
handlers.get('canvas:pointermove')(event(3,500,500));assert.equal(e.yaw,0);
handlers.get('canvas:pointermove')(event(2,120,90));assert.equal(e.yaw,-.08);assert.equal(e.pitch,.03);assert.deepEqual(e.touch,{x:.8,y:-.6});assert.equal(e.touchRunning,true);
handlers.get('canvas:pointerup')(event(3,500,500));assert.equal(e.pointer.down,true);
handlers.get('canvas:pointercancel')(event(2,120,90));assert.equal(e.pointer.down,false);assert.equal(e.touchRunning,true);
handlers.get('window:blur')();assert.deepEqual(e.touch,{x:0,y:0});assert.equal(e.touchRunning,false);
e.setTouch(3,-3);assert.deepEqual(e.touch,{x:1,y:-1});e.setTouchRun(true);e.setPaused(true);assert.deepEqual(e.touch,{x:0,y:0});assert.equal(e.touchRunning,false);
global.matchMedia=()=>({matches:true});const deferred={bedroomQueued:false};TownEngine.prototype.queueBedroom.call(deferred);assert.equal(deferred.bedroomQueued,false);delete global.matchMedia;
console.log('PASS: mobile room loads only on request');
console.log('PASS: Doraemon camera pointer ownership, simultaneous move/run/look, pointer cancellation, blur and modal pause');
