const fs=require('node:fs'),assert=require('node:assert/strict'),ts=require('typescript'),THREE=require('three');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
const {RenderBudget}=require('../lib/town/render-budget.ts');
const {TownVisibility}=require('../lib/town/visibility.ts');
const {TownEngine}=require('../lib/town/engine.ts');
const {TownTraffic}=require('../lib/town/traffic.ts');
const {modelFile,modelVersion,ASSET_VERSION,MOBILE_ASSET_VERSION,MOBILE_ACTOR_VERSION}=require('../lib/town/model-manifest.ts');
const step=(b,seconds,dt,active=true)=>{for(let i=0;i<seconds/dt;i++)b.sample(dt,active);};
const mobile=new RenderBudget(true,3);assert.equal(mobile.ratio,1);
step(mobile,2,1/20);assert.equal(mobile.ratio,1,'Do not react to a short hitch');
step(mobile,3,1/20);assert(mobile.ratio<1);const low=mobile.ratio;step(mobile,3,1/60);assert.equal(mobile.ratio,low,'Avoid quality oscillation');
step(mobile,60,1/20);assert.equal(mobile.ratio,.7);step(mobile,150,1/30);assert.equal(mobile.ratio,1);
const inactive=new RenderBudget(true,3);step(inactive,90,1/8,false);step(inactive,60,.25);assert.equal(inactive.ratio,1,'Loading/background pauses do not lower quality');
assert.equal(mobile.shouldPaint(16.7,0,false),false);assert.equal(mobile.shouldPaint(33.3,0,false),true);assert(mobile.pixelRatio(1200,900)<.7,'Tablet pixels stay bounded');
const desktop=new RenderBudget(false,3);step(desktop,60,1/20);assert.equal(desktop.ratio,1.5);
const lowDpr=new RenderBudget(true,.8);step(lowDpr,60,1/20);step(lowDpr,70,1/60);assert.equal(lowDpr.ratio,.8,'Never exceed actual device DPR');
const scene=new THREE.Group(),near=new THREE.Mesh(new THREE.BoxGeometry(2,2,2)),far=near.clone();far.position.x=80;scene.add(near,far);scene.updateMatrixWorld(true);
const visibility=new TownVisibility(true);visibility.register(scene);visibility.update(new THREE.Vector3(),true);assert(near.layers.isEnabled(0));assert(!far.layers.isEnabled(0));assert.equal(far.visible,true,'Culling must preserve gameplay visibility');
visibility.update(new THREE.Vector3(),false);assert(!far.layers.isEnabled(0));visibility.update(new THREE.Vector3(),false,true);assert(far.layers.isEnabled(0));near.visible=false;visibility.update(new THREE.Vector3(),true);assert.equal(near.visible,false);visibility.unregister(scene);visibility.update(new THREE.Vector3(),true);assert.equal(visibility.culled,0);
const signal=new THREE.MeshPhysicalMaterial({name:'Signal_EW_green',emissive:0x00ff00,transmission:.3}),lamp=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),signal),world=new THREE.Group();world.add(lamp);const traffic=new TownTraffic(world);
TownEngine.prototype.prepareMeshes.call({mobile:true,renderer:{capabilities:{getMaxAnisotropy:()=>4}},atmosphere:{install(){}},water:{install(){}}},world);traffic.refreshSignals();traffic.update(.1,new THREE.Vector3(500,0,0));assert(!(lamp.material instanceof THREE.MeshPhysicalMaterial));assert.equal(traffic.signals[0].material,lamp.material);assert.equal(lamp.material.emissiveIntensity,3.2,'Visible signal uses the converted material');
assert.equal(modelFile('bedroom-v12',true),'mobile-v23/bedroom-v12');assert.equal(modelVersion('bedroom-v12',true),MOBILE_ASSET_VERSION);assert.equal(modelFile('actors/nobita',true),'mobile-v24/actors/nobita');assert.equal(modelVersion('actors/nobita',true),MOBILE_ACTOR_VERSION);assert.equal(modelFile('actors/nobita',false),'actors/nobita');assert.equal(modelVersion('actors/nobita',false),ASSET_VERSION);
console.log('PASS: adaptive resolution hysteresis, DPR ceiling, paused rendering, room visibility restoration and mobile signal materials');
