import * as THREE from 'three';
import type {TownEngine} from './engine';
import {ACTORS,PLACES,TOWN_BOUNDS,inTown,collides,groundHeight,insideHouse,type PlaceId} from './world';
import type {Season} from './weather';
export const TIME_TRIPS=[{id:'spring',title:'春日清晨',season:'spring' as Season,hour:8},{id:'summer',title:'盛夏午后',season:'summer' as Season,hour:15.5},{id:'autumn',title:'秋日黄昏',season:'autumn' as Season,hour:17},{id:'winter',title:'飘雪冬夜',season:'winter' as Season,hour:20}];
export type Activity='none'|'baseball'|'dodge'|'walk'|'time';
export const INITIAL_ADVENTURE={inventory:[] as string[],flowers:0,friendship:0,flying:false,altitude:0,portal:false,portalTarget:'lot' as PlaceId,drawer:false,activity:'none' as Activity,score:0,round:0,remaining:0,cue:'',message:'',best:0,travel:false};
type Projectile={mesh:THREE.Object3D;start:THREE.Vector3;end:THREE.Vector3;age:number;duration:number;from:'pitch'|'player'|'opponent';hit:boolean};
export class TownAdventure {
 state={...INITIAL_ADVENTURE,inventory:[] as string[]};assets=new Map<string,THREE.Group>();propeller?:THREE.Group;door?:THREE.Group;doorHinge?:THREE.Object3D;drawer?:THREE.Group;timeStage=new THREE.Group();drawerOpen=0;portalAge=0;messageUntil=0;clock=0;lastGiftDay=-1;lastFlowerDay=-1;lastTalkDay=-1;walkDistance=0;lastWalk=new THREE.Vector3();challengeAge=0;nextPitch=1;throwCooldown=0;projectiles:Projectile[]=[];savedActors=new Map<string,THREE.Vector3>();travelLeft=0;trip?:typeof TIME_TRIPS[number];bat?:THREE.Group;swing=0;fxTime={value:0};tunnel:THREE.Mesh[]=[];
 constructor(public engine:TownEngine){try{const p=JSON.parse(localStorage.getItem('town-adventure-v1')??'{}');this.state.inventory=Array.isArray(p.inventory)?p.inventory.filter((v:string)=>['bamboo','door'].includes(v)):[];this.state.friendship=Math.max(0,Math.min(5,Number(p.friendship)||0));this.state.flowers=Math.max(0,Math.min(9,Number(p.flowers)||0));this.state.best=Math.max(0,Math.min(99,Number(p.best)||0));}catch{}this.timeStage.visible=false;this.timeStage.position.set(0,120,0);this.engine.scene.add(this.timeStage);
  const colors=['#70cbe1','#adacee','#eee0af'];for(let i=0;i<24;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(3.4,.025,6,80),new THREE.MeshBasicMaterial({color:colors[i%3],transparent:true,opacity:.45,depthWrite:false}));ring.position.set(0,.8,5+i*2.2);ring.rotation.z=i*.07;this.timeStage.add(ring);this.tunnel.push(ring);}const fill=new THREE.PointLight('#a0d3ff',25,8,1.5);fill.position.set(0,2.5,3);this.timeStage.add(fill);
 }
 portalSurface(width:number,height:number){
  const material=new THREE.ShaderMaterial({side:THREE.DoubleSide,uniforms:{time:this.fxTime},
   vertexShader:'varying vec2 portalUv;void main(){portalUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',
   fragmentShader:`varying vec2 portalUv;uniform float time;
    void main(){
     vec2 p=(portalUv-.5)*2.;float r=length(p),a=atan(p.y,p.x);
     float swirl=.5+.5*sin(a*3.+r*11.-time*2.5);
     vec3 c=mix(vec3(.09,.34,.52),vec3(.50,.72,.84),swirl*.45);
     c+=pow(max(0.,1.-r),3.)*.55;gl_FragColor=vec4(c,1.);
     #include <tonemapping_fragment>
     #include <colorspace_fragment>
    }`});
  return new THREE.Mesh(new THREE.PlaneGeometry(width,height),material);
 }

 save(){try{localStorage.setItem('town-adventure-v1',JSON.stringify({inventory:this.state.inventory,flowers:this.state.flowers,friendship:this.state.friendship,best:this.state.best}));}catch{}}
 say(message:string){this.state.message=message;this.messageUntil=this.clock+6;this.engine.emit();}
 addAsset(id:string,source:THREE.Group){this.assets.set(id,source);if(id==='drawer'){this.drawer=source;this.drawer.name='interactive_desk_drawer';const portal=this.portalSurface(.48,.24);portal.rotation.x=-Math.PI/2;portal.position.set(-10.59,3.761,-1.02);portal.name='drawer_time_window';portal.visible=false;source.add(portal);this.engine.world!.add(source);}if(id==='time-machine'){source.scale.setScalar(.9);this.timeStage.add(source);}}
 getGift(){if(this.engine.state.actor?.id!=='doraemon'){this.say('先到哆啦A梦身边，和他聊聊吧。');return false;}for(const id of ['bamboo','door'])if(!this.state.inventory.includes(id))this.state.inventory.push(id);this.save();this.engine.sound.effect('treasure');this.engine.closeDialogue();this.say('获得竹蜻蜓和任意门！二楼书桌的抽屉里，还藏着时光机。');return true;}
 fly(){if(!this.state.inventory.includes('bamboo')){this.say('和哆啦A梦聊天，可以获得竹蜻蜓。');return false;}if(this.state.flying)return this.land();if(this.engine.state.inside||this.state.activity!=='none'){this.say('先走到室外的开阔处，再戴上竹蜻蜓。');return false;}this.state.flying=true;this.state.portal=false;if(this.door)this.door.visible=false;this.engine.walkTarget=null;
  if(!this.propeller){this.propeller=(this.assets.get('bamboo')?.clone(true)??new THREE.Group());this.propeller.position.set(0,1.405,0);this.engine.player.add(this.propeller);}this.propeller.visible=true;this.engine.sound.effect('bamboo');this.say('竹蜻蜓启动 · WASD 飞行，空格上升，Ctrl 下降，C 安全着陆');return true;}
 land(silent=false){if(!this.state.flying)return true;const p=this.engine.playerPosition;let spot:THREE.Vector3|undefined;for(let radius=0;radius<=8&&!spot;radius+=.5)for(let i=0;i<(radius===0?1:16);i++){const x=p.x+Math.sin(i*Math.PI/8)*radius,y=-p.z+Math.cos(i*Math.PI/8)*radius,h=groundHeight(x,y,.053,this.engine.groundSurfaces);if(inTown(x,y,.4)&&!insideHouse(x,y)&&!collides(x,y,h,this.engine.colliders,.27)&&!this.engine.traffic?.collides(x,y,h,.27)){spot=new THREE.Vector3(x,h,-y);break;}}
  if(!spot){this.say('下方没有安全落脚处，往街道上空飞一点。');return false;}p.copy(spot);this.state.flying=false;this.state.altitude=0;if(this.propeller)this.propeller.visible=false;this.engine.sound.stop('bamboo');if(!silent)this.say('已安全着陆。');return true;}
 flightMove(dt:number){if(!this.state.flying)return false;const e=this.engine,k=e.keys,p=e.playerPosition;const f=(k.has('KeyW')||k.has('ArrowUp')?1:0)-(k.has('KeyS')||k.has('ArrowDown')?1:0)-e.touch.y,r=(k.has('KeyD')||k.has('ArrowRight')?1:0)-(k.has('KeyA')||k.has('ArrowLeft')?1:0)+e.touch.x,angle=e.state.mode==='first'?e.yaw:e.azimuth;
  const direction=new THREE.Vector3(-Math.sin(angle)*f+Math.cos(angle)*r,0,-Math.cos(angle)*f-Math.sin(angle)*r);if(direction.lengthSq()>0)direction.normalize();const ground=groundHeight(p.x,-p.z,.053,e.groundSurfaces);const vertical=(k.has('Space')?1:0)-(k.has('ControlLeft')||k.has('ControlRight')?1:0);const ny=THREE.MathUtils.clamp(p.y+(p.y<ground+1.6?1.7:vertical*2.3)*dt,ground+.10,18);if(!collides(p.x,-p.z,ny,e.colliders))p.y=ny;
  const x=THREE.MathUtils.clamp(p.x+direction.x*3.2*dt,TOWN_BOUNDS.x0,TOWN_BOUNDS.x1),z=THREE.MathUtils.clamp(p.z+direction.z*3.2*dt,-TOWN_BOUNDS.y1,-TOWN_BOUNDS.y0);if(!collides(x,-p.z,p.y,e.colliders))p.x=x;if(!collides(p.x,-z,p.y,e.colliders))p.z=z;
  e.player.position.copy(p);if(direction.lengthSq())e.player.quaternion.slerp(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),Math.atan2(direction.x,direction.z)),Math.min(1,dt*5));e.targetGoal.copy(p).add(new THREE.Vector3(0,1,0));e.idlePlayer();this.state.altitude=Math.max(0,p.y-ground);return true;}
 openPortal(target:PlaceId){if(!this.state.inventory.includes('door')){this.say('任意门还在哆啦A梦的口袋里。');return false;}if(this.state.activity!=='none'){this.say('先结束当前活动，再打开任意门。');return false;}if(!this.land(true))return false;this.state.portalTarget=target;this.state.portal=true;this.portalAge=0;
  if(this.door)this.door.removeFromParent();this.door=this.assets.get('door')?.clone(true)??new THREE.Group();const e=this.engine,a=e.state.mode==='first'?e.yaw:e.azimuth;let position:THREE.Vector3|undefined;for(const radius of [1.6,2.2,2.8]){for(const shift of [0,.7,-.7,1.4,-1.4]){const x=e.playerPosition.x-Math.sin(a+shift)*radius,z=e.playerPosition.z-Math.cos(a+shift)*radius,h=groundHeight(x,-z,e.playerPosition.y,e.groundSurfaces);if(inTown(x,-z,.6)&&Math.abs(h-e.playerPosition.y)<.3&&!collides(x,-z,h,e.colliders,.54)&&!e.traffic?.collides(x,-z,h,.54)){position=new THREE.Vector3(x,h,z);break;}}if(position)break;}if(!position){this.state.portal=false;this.say('这里放不下任意门，去街道或空地的开阔处试试。');return false;}this.door.position.copy(position);this.door.rotation.y=Math.atan2(e.playerPosition.x-position.x,e.playerPosition.z-position.z);this.doorHinge=this.door.getObjectByName('Door_HingePivot');const portal=this.portalSurface(.83,1.90);portal.position.set(0,1.02,-.04);this.door.add(portal);e.scene.add(this.door);this.engine.sound.effect('portal');this.say('任意门通往'+PLACES.find(p=>p.id===target)?.title+'，走进门或点击“穿过任意门”。');return true;}
 enterPortal(){if(!this.state.portal)return false;const target=this.state.portalTarget;this.state.portal=false;if(this.door)this.door.visible=false;this.engine.teleport(target);this.engine.sound.effect('portal');this.say('任意门已抵达：'+PLACES.find(p=>p.id===target)?.title);return true;}
 openDrawer(){const p=this.engine.playerPosition;if(!this.engine.state.floor||Math.hypot(p.x+10.59,p.z+1.15)>2.9){this.say('到二楼书桌前，打开中间的浅抽屉。');return false;}this.state.drawer=!this.state.drawer;this.engine.sound.effect('portal');this.say(this.state.drawer?'抽屉里出现了时光隧道。进入时光机，选择想去的季节吧。':'轻轻合上了抽屉。');return true;}
 enterTime(){if(!this.state.drawer||this.engine.state.floor!==1){this.say('先打开二楼书桌的抽屉。');return false;}this.state.activity='time';this.engine.closeDialogue();this.engine.world!.visible=false;this.engine.player.visible=false;this.engine.ring.visible=false;this.timeStage.visible=true;this.engine.sound.effect('portal');this.say('坐稳啦！选择一次春、夏、秋、冬的时光旅行。');return true;}
 travel(id:string){if(this.state.activity!=='time'||this.state.travel)return false;const trip=TIME_TRIPS.find(t=>t.id===id);if(!trip)return false;this.trip=trip;this.state.travel=true;this.travelLeft=3.2;this.engine.sound.effect('portal');return true;}
 leaveTime(){this.state.activity='none';this.state.travel=false;this.timeStage.visible=false;if(this.engine.world)this.engine.world.visible=true;this.engine.teleport('bedroom');}
 collectFlower(){const p=this.engine.playerPosition;if(this.lastFlowerDay===this.engine.weather.state.day){this.say('今天已经取过一朵花了，给花园留一些吧。');return false;}if(Math.min(Math.hypot(p.x+9.6,p.z-6.3),Math.hypot(p.x+9,p.z-24.3))>5){this.say('大雄家或静香家的花园边，有可以送给朋友的小花。');return false;}this.lastFlowerDay=this.engine.weather.state.day;this.state.flowers++;this.save();this.engine.sound.effect('treasure');this.say('得到一朵小花，可以送给静香。');return true;}
 friend(action:'talk'|'flower'|'walk'){if(this.engine.state.actor?.id!=='shizuka')return false;const day=this.engine.weather.state.day;if(action==='talk'){if(this.lastTalkDay===day){this.say('静香：今天聊得很开心，我们再去走走吧。');return false;}this.lastTalkDay=day;this.state.friendship=Math.min(5,this.state.friendship+1);this.say('静香笑着听你说完今天的趣事，好感 +1。');}
  if(action==='flower'){if(this.state.flowers<1){this.say('先到家门口的花园取一朵小花。');return false;}if(this.lastGiftDay===day){this.say('静香：今天这朵花就已经很开心啦。');return false;}this.lastGiftDay=day;this.state.flowers--;this.state.friendship=Math.min(5,this.state.friendship+1);this.engine.sound.effect('treasure');this.say('静香：谢谢你，大雄。明天也一起走回家吧。好感 +1。');}
  if(action==='walk'){if(this.state.friendship<2){this.say('先多聊聊或送一朵花，好感达到 2 后就能约她散步。');return false;}if(this.state.activity!=='none')return false;this.state.activity='walk';this.walkDistance=0;this.lastWalk.copy(this.engine.playerPosition);if(this.engine.ecosystem)this.engine.ecosystem.companion='shizuka';this.engine.closeDialogue();this.say('和静香一起散步 · 带她慢慢走 25 米，她会跟着你。');}
  this.save();return true;}
 startGame(kind:'baseball'|'dodge'){const id=this.engine.state.actor?.id;if(id!=='gian'&&id!=='suneo'){this.say('先和胖虎或小夫说一声，再开始挑战。');return false;}this.stopActivity(false);this.engine.closeDialogue();this.engine.teleport('lot');this.state.activity=kind;this.state.score=0;this.state.round=0;this.state.remaining=kind==='baseball'?5:35;this.challengeAge=0;this.nextPitch=1;this.engine.playerPosition.set(18,.213,0);this.engine.player.position.copy(this.engine.playerPosition);this.engine.setMode('orbit');this.engine.distance=14;this.engine.azimuth=.15;
  for(const [id,x,y] of [['gian',18,6],['suneo',21,5]] as const){const actor=this.engine.world?.getObjectByName('actor_'+id);if(actor){this.savedActors.set(id,actor.position.clone());actor.position.set(x,.213,-y);actor.rotation.y=Math.PI;this.engine.ecosystem?.held.add(id);}}
  if(kind==='baseball'){this.bat=this.assets.get('bat')?.clone(true)??new THREE.Group();this.bat.position.set(.42,.68,.25);this.bat.rotation.z=-.45;this.engine.player.add(this.bat);}
  this.say(kind==='baseball'?'棒球练习 · 看球靠近，空格挥棒！一共 5 球。':'空地投球对决 · WASD 闪避来球，空格向胖虎和小夫投球。');return true;}
 makeBall(from:Projectile['from'],start:THREE.Vector3,end:THREE.Vector3,duration:number){const mesh=this.assets.get('baseball')?.clone(true)??new THREE.Mesh(new THREE.SphereGeometry(.037,16,12),new THREE.MeshStandardMaterial({color:'#f3e6cb',roughness:.75}));mesh.position.copy(start);this.engine.scene.add(mesh);this.projectiles.push({mesh,start:start.clone(),end:end.clone(),age:0,duration,from,hit:false});}
 action(){if(this.state.activity==='baseball'){this.swing=.28;const ball=this.projectiles.find(p=>p.from==='pitch'&&!p.hit);if(ball&&Math.abs(ball.age/ball.duration-.88)<.14&&ball.mesh.position.distanceTo(this.engine.playerPosition.clone().add(new THREE.Vector3(0,.85,0)))<1.5){ball.hit=true;ball.start.copy(ball.mesh.position);ball.end.set(15+Math.sin(this.clock)*3,1,-12);ball.age=0;ball.duration=1.45;this.state.score++;this.state.cue='好球！';this.engine.sound.effect('baseball');}else this.state.cue='挥空了，等球再近一点';return true;}
  if(this.state.activity==='dodge'&&this.throwCooldown<=0){this.throwCooldown=.75;const id=this.state.round%2?'suneo':'gian',a=this.engine.world?.getObjectByName('actor_'+id);if(a){this.makeBall('player',this.engine.playerPosition.clone().add(new THREE.Vector3(0,.9,0)),a.position.clone().add(new THREE.Vector3(Math.sin(this.clock)*.3,.9,0)),.65);this.engine.wave();}return true;}return false;}
 stopActivity(announce=true){const was=this.state.activity;if(was==='time'){this.leaveTime();return;}if(was==='baseball'||was==='dodge'){this.state.best=Math.max(this.state.best,this.state.score);if(announce)this.say('挑战结束 · 命中 '+this.state.score+' 次，个人最佳 '+this.state.best+' 次。');this.save();}this.state.activity='none';this.state.cue='';this.projectiles.forEach(p=>p.mesh.removeFromParent());this.projectiles=[];this.bat?.removeFromParent();for(const [id,p] of this.savedActors){const a=this.engine.world?.getObjectByName('actor_'+id);a?.position.copy(p);this.engine.ecosystem?.held.delete(id);}this.savedActors.clear();if(this.engine.ecosystem)this.engine.ecosystem.companion=null;}
 onTeleport(){if(this.state.activity==='time'){this.state.activity='none';this.state.travel=false;this.timeStage.visible=false;if(this.engine.world)this.engine.world.visible=true;}this.land(true);this.state.portal=false;if(this.door)this.door.visible=false;if(this.state.activity!=='none')this.stopActivity(false);}
 update(dt:number){this.clock+=dt;this.fxTime.value=this.clock;if(this.clock>this.messageUntil)this.state.message='';if(this.propeller&&this.state.flying){const rotor=this.propeller.getObjectByName('Bamboo_Rotor');if(rotor)rotor.rotation.y+=dt*35;}
  this.portalAge+=dt;if(this.doorHinge&&this.state.portal)this.doorHinge.rotation.y=-Math.min(1,this.portalAge*1.5)*Math.PI*.58;if(this.state.portal&&this.door&&this.portalAge>.8&&this.engine.playerPosition.distanceTo(this.door.position)<.7)this.enterPortal();
  this.drawerOpen=THREE.MathUtils.damp(this.drawerOpen,this.state.drawer?.34:0,5,dt);if(this.drawer){this.drawer.position.z=-this.drawerOpen;const portal=this.drawer.getObjectByName('drawer_time_window');if(portal)portal.visible=this.drawerOpen>.15;}
  if(this.state.activity==='time'){for(let i=0;i<this.tunnel.length;i++){const ring=this.tunnel[i];ring.position.z=2+((i*2.2-this.clock*(this.state.travel?14:1))%52+52)%52;ring.rotation.z=this.clock*.06+i*.12;}for(const name of ['TM_Gauge_TIME_Needle','TM_Gauge_ENERGY_Needle']){const needle=this.timeStage.getObjectByName(name);if(needle)needle.rotation.y=Math.sin(this.clock*(this.state.travel?7:.8))*.55;}if(this.state.travel){this.travelLeft-=dt;if(this.travelLeft<=0&&this.trip){this.engine.weather.setSeason(this.trip.season);this.engine.weather.setHour(this.trip.hour);const title=this.trip.title;this.leaveTime();this.say('时光旅行抵达：'+title+'。走下楼看看小镇的变化吧。');}}return;}
  if(this.state.activity==='walk'){const delta=this.lastWalk.distanceTo(this.engine.playerPosition);const companion=this.engine.ecosystem?.actorPosition('shizuka');if(delta<.2&&companion&&companion.distanceTo(this.engine.playerPosition)<3)this.walkDistance+=delta;this.lastWalk.copy(this.engine.playerPosition);this.state.cue='一起散步 '+Math.floor(this.walkDistance)+' / 25 米';if(this.walkDistance>=25){this.state.friendship=Math.min(5,this.state.friendship+1);this.stopActivity(false);this.save();this.say('静香：和你散步真开心。我们明天还一起回家，好吗？好感 +1。');}}
  if(this.state.activity!=='baseball'&&this.state.activity!=='dodge')return;this.challengeAge+=dt;this.throwCooldown-=dt;if(this.state.activity==='dodge'){for(const [id,cx,phase] of [['gian',18,0],['suneo',21,2]] as const){const actor=this.engine.world?.getObjectByName('actor_'+id);if(actor)actor.position.x=cx+Math.sin(this.challengeAge*.95+phase)*1.15;}}this.swing=Math.max(0,this.swing-dt);if(this.bat)this.bat.rotation.y=Math.sin(this.swing/.28*Math.PI)*2.3;
  if(this.challengeAge>=this.nextPitch){if(this.state.activity==='baseball'&&this.state.round>=5){if(!this.projectiles.length)this.stopActivity();}
   else{this.state.round++;this.nextPitch=this.challengeAge+(this.state.activity==='baseball'?3.5:2.5);const id=this.state.round%2?'gian':'suneo',a=this.engine.world?.getObjectByName('actor_'+id);if(a){this.engine.wave(id);this.makeBall(this.state.activity==='baseball'?'pitch':'opponent',a.position.clone().add(new THREE.Vector3(0,1.1,0)),this.engine.playerPosition.clone().add(new THREE.Vector3(0,.85,.25)),this.state.activity==='baseball'?1.5:1.4);}this.state.cue='球来了！';}}
  for(const p of [...this.projectiles]){p.age+=dt;const t=Math.min(1,p.age/p.duration);p.mesh.position.lerpVectors(p.start,p.end,t);p.mesh.position.y+=Math.sin(t*Math.PI)*(p.hit?2:.22);p.mesh.rotation.x+=dt*18;if(p.from==='pitch'&&!p.hit&&t>.76&&t<.99)this.state.cue='现在挥棒！';
   if(p.age>=p.duration){if(p.from==='opponent'&&this.engine.playerPosition.clone().add(new THREE.Vector3(0,.85,0)).distanceTo(p.end)<.7){this.state.score=Math.max(0,this.state.score-1);this.state.cue='被碰到啦，左右闪避！';}if(p.from==='player'){const hit=['gian','suneo'].some(id=>this.engine.world!.getObjectByName('actor_'+id)!.position.clone().add(new THREE.Vector3(0,.9,0)).distanceTo(p.end)<.75);if(hit){this.state.score++;this.state.cue='命中！';this.engine.sound.effect('baseball');}}p.mesh.removeFromParent();this.projectiles.splice(this.projectiles.indexOf(p),1);}}
  this.state.remaining=this.state.activity==='baseball'?Math.max(0,5-this.state.round):Math.max(0,35-this.challengeAge);if(this.state.activity==='dodge'&&this.challengeAge>=35)this.stopActivity();
 }
 timeCamera(){const e=this.engine;e.camera.position.set(2.5,122.1,4);e.camera.lookAt(0,120.5,0);e.player.visible=false;e.ring.visible=false;const spin=this.clock*(this.state.travel?3:.25);this.timeStage.rotation.y=Math.sin(spin*.15)*.04;}
 snapshot(){return{...this.state,inventory:[...this.state.inventory]};}
}
