import * as THREE from 'three';
import type {TownSky} from './sky';
import type {TownAtmosphere} from './atmosphere';
export type Season='spring'|'summer'|'autumn'|'winter';
export const SEASONS:{id:Season;name:string;detail:string}[]=[{id:'spring',name:'春',detail:'花瓣与新绿'},{id:'summer',name:'夏',detail:'蝉鸣与浓荫'},{id:'autumn',name:'秋',detail:'落叶与金色傍晚'},{id:'winter',name:'冬',detail:'细雪与安静街巷'}];
export const DAYLIGHT:Record<Season,[number,number]>={spring:[5.7,18.2],summer:[4.7,19],autumn:[6,17.4],winter:[6.8,16.7]};
export const INITIAL_WEATHER={season:'summer' as Season,hour:15.5,day:1,auto:true,time:'15:30',night:false};
export class TownWeather {
 state={...INITIAL_WEATHER};sunOffset=new THREE.Vector3(-28,48,35);materials:{m:THREE.MeshStandardMaterial;base:THREE.Color;kind:string}[]=[];particles=new THREE.Group();types=new Map<string,THREE.InstancedMesh>();elapsed=0;dummy=new THREE.Object3D();
 constructor(public scene:THREE.Scene,public sky:TownSky,public sun:THREE.DirectionalLight,public hemi:THREE.HemisphereLight,public breeze:TownAtmosphere){scene.add(this.particles);this.particles.name='seasonal_air';}
 install(world:THREE.Object3D){const seen=new Set<THREE.Material>();world.traverse(o=>{if(o instanceof THREE.Mesh)for(const m of Array.isArray(o.material)?o.material:[o.material]){if(seen.has(m)||!(m instanceof THREE.MeshStandardMaterial))continue;seen.add(m);if(/V7_Turf|GrassBlade|V7_Soil|V10_WhiteClover/.test(m.name))this.materials.push({m,base:m.color.clone(),kind:/Soil/.test(m.name)?'soil':'grass'});}});this.setSeason(this.state.season);}
 addAsset(gltf:THREE.Group){gltf.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const name=o.name.toLowerCase();const kind=/snow/.test(name)?'winter':/petal/.test(name)?'spring':/leaf/.test(name)?'autumn':null;if(!kind||this.types.has(kind))return;const geometry=o.geometry.clone();geometry.applyMatrix4(o.matrixWorld);geometry.center();const mat=Array.isArray(o.material)?o.material[0]:o.material;const mesh=new THREE.InstancedMesh(geometry,mat,kind==='winter'?260:100);mesh.frustumCulled=false;mesh.castShadow=false;this.types.set(kind,mesh);this.particles.add(mesh);});}
 setSeason(season:Season){this.state.season=season;const colors={spring:'#d5ecb6',summer:'#ffffff',autumn:'#c6aa6e',winter:'#c4c9b6'};for(const {m,base,kind} of this.materials){m.color.copy(base);if(kind==='grass')m.color.multiply(new THREE.Color(colors[season]));if(season==='winter')m.color.lerp(new THREE.Color('#cad0c8'),kind==='grass'?.48:.12);}
  this.breeze.seasonAmount.value=season==='autumn'?.82:season==='winter'?.4:0;this.breeze.strength.value=season==='autumn'?1.3:season==='winter'?.7:1;}
 setHour(hour:number){this.state.hour=((hour%24)+24)%24;this.refreshClock();}
 refreshClock(){const minutes=Math.floor(this.state.hour*60);this.state.time=String(Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');const [rise,set]=DAYLIGHT[this.state.season];this.state.night=this.state.hour<rise||this.state.hour>=set;}
 update(dt:number,player:THREE.Vector3,inside:boolean,bedroom=false){this.elapsed+=dt;if(this.state.auto){this.state.hour+=dt*.025;if(this.state.hour>=24){this.state.hour-=24;this.state.day++;if((this.state.day-1)%4===0)this.setSeason(SEASONS[(SEASONS.findIndex(s=>s.id===this.state.season)+1)%4].id);}}this.refreshClock();
  const [rise,set]=DAYLIGHT[this.state.season],hour=this.state.hour,dayAngle=(hour-rise)/(set-rise)*Math.PI;const elevation=hour>=rise&&hour<set?Math.sin(dayAngle):-Math.sin(((hour<rise?hour+24:hour)-set)/(24-set+rise)*Math.PI),day=THREE.MathUtils.smoothstep(elevation,-.10,.38);this.sky.setTime(this.state.hour,rise,set);
  const azimuth=dayAngle;this.sunOffset.set(-Math.cos(azimuth)*43,Math.max(8,Math.abs(elevation)*52),25);this.sun.intensity=.15+day*2.85;this.sun.color.set(day<.1?'#b8d7ff':elevation<.3?'#ffc092':'#fff0d2');this.hemi.color.set(bedroom?'#efcda1':'#d9eeff');this.hemi.groundColor.set(bedroom?'#87663e':'#a59775');this.hemi.intensity=(.2+1.2*day)*(bedroom?.40:1);this.scene.environmentIntensity=(.09+.26*day)*(bedroom?.7:1);
  const fog=this.scene.fog as THREE.FogExp2;fog.color.copy(new THREE.Color('#122338')).lerp(new THREE.Color(elevation<.30?'#d6beb0':'#bfd7de'),day);fog.density=this.state.season==='winter'?.006:.0035;this.scene.background=fog.color;
  this.particles.visible=!inside;for(const [season,mesh] of this.types){mesh.visible=season===this.state.season;if(!mesh.visible)continue;for(let i=0;i<mesh.count;i++){const seed=i*2.39996;const x=Math.sin(seed)*15+Math.sin(this.elapsed*.32+i)*.55,z=Math.cos(seed*1.31)*14,y=9-((this.elapsed*(season==='winter'?.55:.8)+i*.179)%9);this.dummy.position.set(player.x+x,.2+y,player.z+z);this.dummy.rotation.set(this.elapsed*.3+seed,seed+this.elapsed*.5,seed);this.dummy.scale.setScalar(season==='winter'?.85:.75);this.dummy.updateMatrix();mesh.setMatrixAt(i,this.dummy.matrix);}mesh.instanceMatrix.needsUpdate=true;}
 }
 snapshot(){return{...this.state};}
}
