import type {TownEngine} from './engine';
import {ACTORS,PLACES} from './world';
type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
export function registerTownTools(engine:TownEngine){
 const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return ()=>{};
 const lifecycle=new AbortController();
 const tools:Tool[]=[
  {name:'read_town_state',title:'查看小镇探索状态',description:'Read current place, camera, position and available destinations without changing the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({ready:engine.state.ready,progress:engine.state.progress,error:engine.state.error,house:engine.state.house,quality:engine.quality,assetRevision:engine.assetRevision,adventure:engine.adventure.snapshot(),weather:engine.weather.snapshot(),audio:engine.sound.snapshot(),playAssets:[...engine.adventure.assets.keys()],environmentLife:engine.ecosystem?.snapshot(),traffic:engine.traffic?.snapshot(),sky:engine.sky.snapshot(),river:{surfaces:engine.water.surfaces,flowTime:engine.water.time.value},interiorLight:engine.interiorLight.snapshot(),detailAssets:{neighborhood:!!engine.world?.getObjectByName('v11_home_lower'),shizuka:!!engine.world?.getObjectByName('v11_shizuka_upper'),garden:!!engine.world?.getObjectByName('v9_garden'),stairs:!!engine.world?.getObjectByName('v11_home_stairs'),closet:!!engine.world?.getObjectByName('v12_closet_slide'),hill:!!engine.world?.getObjectByName('Hill_Ascent_Trail')},renderHealth:{estimatedFps:Math.round(1/engine.frameSeconds),shaderErrors:engine.shaderErrors,calls:engine.renderer.info.render.calls,triangles:engine.renderer.info.render.triangles},wind:{meshes:engine.atmosphere.windMeshes,time:engine.atmosphere.time.value},surfaceDetailLoaded:!!engine.world?.getObjectByName('surface_detail'),facadeDetailLoaded:!!engine.world?.getObjectByName('facade_ground'),characterActions:[...engine.motions].map(([id,m])=>({id,current:m.current,clips:[...m.actions.keys()]})),place:engine.state.place,mode:engine.state.mode,floor:engine.state.floor,position:{x:engine.playerPosition.x,y:-engine.playerPosition.z,height:engine.playerPosition.y},places:PLACES.map(p=>({id:p.id,title:p.title}))})},
  {name:'navigate_town',title:'前往小镇地点',description:'Move the player to a named town destination using the same game navigation as the pocket destination controls, optionally change camera.',inputSchema:{type:'object',properties:{place:{type:'string',enum:PLACES.map(p=>p.id)},mode:{type:'string',enum:['orbit','first']}},required:['place'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object')throw new Error('Expected destination object');const v=input as Record<string,unknown>;const p=PLACES.find(p=>p.id===v.place);if(!p||Object.keys(v).some(k=>k!=='place'&&k!=='mode')||(v.mode!==undefined&&v.mode!=='orbit'&&v.mode!=='first'))throw new Error('Invalid destination or camera mode');if(!engine.state.ready)throw new Error('Town is still loading');engine.teleport(p.id);if(v.mode)engine.setMode(v.mode as 'first'|'orbit');return{place:engine.state.place,mode:engine.state.mode,position:{x:engine.playerPosition.x,y:-engine.playerPosition.z,height:engine.playerPosition.y}};}},
  {name:'meet_town_neighbor',title:'找小镇里的伙伴',description:'Use the visible pocket panel action to meet a neighbor and open their conversation.',inputSchema:{type:'object',properties:{person:{type:'string',enum:ACTORS.map(a=>a.id)}},required:['person'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const v=input as {person:string};if(!v||!ACTORS.some(a=>a.id===v.person))throw new Error('Choose a town neighbor');return{opened:engine.meetActor(v.person),person:engine.state.actor?.id};}},
  {name:'use_town_action',title:'使用道具或参加活动',description:'Perform a visible game action: receive Doraemon gadgets during dialogue, fly/land, use a door, open the bedroom drawer, travel seasons, play ball, or interact with Shizuka. Normal in-game prerequisites apply.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['gift','fly','land','open_portal','enter_portal','open_drawer','enter_time','travel','leave_time','collect_flower','friend_talk','friend_gift','friend_walk','baseball','dodge','swing','end_activity','close_dialogue','interact']},destination:{type:'string',enum:PLACES.map(p=>p.id)},trip:{type:'string',enum:['spring','summer','autumn','winter']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!engine.state.ready)throw new Error('Town is still loading');const v=input as {action:string;destination?:typeof PLACES[number]['id'];trip?:string};if(!v||typeof v.action!=='string')throw new Error('Choose an action');const a=engine.adventure;let result:unknown;
   switch(v.action){case 'gift':result=a.getGift();break;case 'fly':result=a.fly();break;case 'land':result=a.land();break;case 'open_portal':if(!PLACES.some(p=>p.id===v.destination))throw new Error('Choose a door destination');result=a.openPortal(v.destination!);break;case 'enter_portal':result=a.enterPortal();break;case 'open_drawer':result=a.openDrawer();break;case 'enter_time':result=a.enterTime();break;case 'travel':result=a.travel(v.trip??'');break;case 'leave_time':a.leaveTime();break;case 'collect_flower':result=a.collectFlower();break;case 'friend_talk':result=a.friend('talk');break;case 'friend_gift':result=a.friend('flower');break;case 'friend_walk':result=a.friend('walk');break;case 'baseball':result=a.startGame('baseball');break;case 'dodge':result=a.startGame('dodge');break;case 'swing':result=a.action();break;case 'end_activity':a.stopActivity();break;case 'close_dialogue':engine.closeDialogue();break;case 'interact':engine.interact();break;default:throw new Error('Unknown action');}engine.emit();return{accepted:result!==false,adventure:a.snapshot()};}},
  {name:'set_town_season_time',title:'调整小镇季节与时间',description:'Use the settings panel controls to set spring, summer, autumn or winter; choose an hour and whether time flows.',inputSchema:{type:'object',properties:{season:{type:'string',enum:['spring','summer','autumn','winter']},hour:{type:'number',minimum:0,maximum:23.99},auto:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const v=input as {season?:'spring'|'summer'|'autumn'|'winter';hour?:number;auto?:boolean};if(!v||typeof v!=='object')throw new Error('Expected settings');if(v.season){if(!['spring','summer','autumn','winter'].includes(v.season))throw new Error('Unknown season');engine.weather.setSeason(v.season);}if(v.hour!==undefined){if(!Number.isFinite(v.hour)||v.hour<0||v.hour>=24)throw new Error('Hour out of range');engine.weather.setHour(v.hour);}if(v.auto!==undefined){if(typeof v.auto!=='boolean')throw new Error('Expected auto boolean');engine.weather.state.auto=v.auto;}engine.emit();return engine.weather.snapshot();}},
 ];
 for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(e=>console.warn('Town tool registration unavailable',e));}catch(e){console.warn('Town tool registration unavailable',e);}}
 return()=>lifecycle.abort();
}
