"""Editable Blender panda residence. All architecture, furniture and props are geometry.

Run with Blender --background --python tools/build-panda-home.py.
Local authoring: +Y is rear, +Z up; glTF/Godot: +Z is entrance, +Y up.
Panda character is separately generated by Tripo, never synthesized by this script.
"""
from pathlib import Path
import bpy, math, random, json, sys, os
import numpy as np
from mathutils import Vector

ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/'worlds/frog/source/assets'
NATIVE=ROOT/'worlds/frog/blender'
EVIDENCE=ROOT/'docs/evidence/panda-home/details-02'
for d in [ASSETS,NATIVE,EVIDENCE]:d.mkdir(parents=True,exist_ok=True)
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
rng=random.Random(912)
TAU=math.tau
def mat(name,color,rough=.85,emission=0,texture=None):
 # Textured palette colors are picked display/sRGB swatches. Convert their
 # chosen darker appearance into a true linear albedo first; constants below
 # are already linear. Blender's packed 8-bit sRGB images then need encoding.
 if texture:color=tuple(c/12.92 if c<=.04045 else ((c+.055)/1.055)**2.4 for c in color)
 m=bpy.data.materials.new(name);m.use_nodes=True;m.diffuse_color=(*color,1)
 s=next((n for n in m.node_tree.nodes if n.type=='BSDF_PRINCIPLED'),None)
 if s is None:s=m.node_tree.nodes.new('ShaderNodeBsdfPrincipled')
 out=next((n for n in m.node_tree.nodes if n.type=='OUTPUT_MATERIAL'),None)
 if out is None:out=m.node_tree.nodes.new('ShaderNodeOutputMaterial')
 m.node_tree.links.new(s.outputs['BSDF'],out.inputs['Surface'])
 s.inputs['Base Color'].default_value=(*color,1);s.inputs['Roughness'].default_value=rough
 if emission:s.inputs['Emission Color'].default_value=(*color,1);s.inputs['Emission Strength'].default_value=emission
 if texture:
  n=512;yy,xx=np.mgrid[0:n,0:n]/n;field=np.zeros((n,n));rand=np.random.default_rng(912+len(bpy.data.materials))
  for grid,w in [(3,.55),(11,.28),(43,.13),(127,.04)]:
   a=rand.random((grid+1,grid+1));a[-1,:]=a[0,:];a[:,-1]=a[:,0];gx=xx*grid;gy=yy*grid;i=gx.astype(int);j=gy.astype(int);u=gx-i;v=gy-j;u=u*u*(3-2*u);v=v*v*(3-2*v)
   field+=w*((1-v)*((1-u)*a[j,i]+u*a[j,i+1])+v*((1-u)*a[j+1,i]+u*a[j+1,i+1]))
  if texture=='wood':field=.50+.17*np.sin(xx*TAU*16+np.sin(yy*TAU*2)*.8+field*8)+.13*field
  if texture=='weave':field=.5+.1*np.sin(xx*TAU*64)+.1*np.sin(yy*TAU*64)+field*.06
  pixels=np.ones((n,n,4),dtype=np.float32)
  for c,base in enumerate(color):pixels[:,:,c]=base*(.83+.34*field)
  # Confirmed by 3-swatch emission + GLB roundtrip calibration: linear .25
  # constant matches encoded .5371 image pixels, not raw .25 image pixels.
  pixels[:,:,:3]=np.where(pixels[:,:,:3]<.0031308,pixels[:,:,:3]*12.92,1.055*np.power(pixels[:,:,:3],1/2.4)-.055)
  im=bpy.data.images.new(name+' packed albedo',n,n);im.pixels.foreach_set(pixels.ravel());im.pack()
  node=m.node_tree.nodes.new('ShaderNodeTexImage');node.image=im;m.node_tree.links.new(node.outputs['Color'],s.inputs['Base Color'])
 return m
rock=mat('Panda mineral limestone',(.39,.375,.34),texture='rock')
grout=mat('Panda recessed stone joints',(.035,.04,.033))
fissure_mat=mat('Panda natural stone hairlines',(.060,.057,.049))
stone=[mat('Panda flagstone '+str(i),(.28+i*.023,.30+i*.022,.29+i*.022),texture='rock') for i in range(4)]
wood=mat('Panda warm oak grain',(.30,.17,.075),texture='wood')
edge=mat('Panda oak endgrain',(.39,.235,.11),texture='wood')
bamboo=mat('Panda golden bamboo',(.49,.33,.135),texture='wood')
node_mat=mat('Panda bamboo nodes',(.13,.075,.025))
green=mat('Panda sage linen',(.34,.39,.21),texture='weave')
straw=mat('Panda woven natural straw',(.51,.385,.20),texture='weave')
gold=mat('Panda ochre bed linen',(.63,.43,.18),texture='weave')
cream=mat('Panda unbleached linen',(.74,.685,.54),texture='weave')
celadon=mat('Panda glazed celadon',(.23,.385,.32),rough=.24)
teapot_mat=mat('Panda iron tea kettle',(.075,.073,.058),rough=.43)
paper=mat('Panda warm diffuse window',(.91,.77,.48),emission=.45)
lamp_mat=mat('Panda lantern paper',(.88,.57,.22),emission=1.6)
leaf_mat=mat('Panda living bamboo leaves',(.16,.28,.055))
leaf_light=mat('Panda leaf light',(.25,.37,.095))
ink=mat('Panda ink mountains',(.19,.22,.19))
ink_light=mat('Panda distant ink wash',(.39,.42,.35))

def mesh(name,vertices,faces,material,uv=None):
 me=bpy.data.meshes.new(name);me.from_pydata(vertices,[],faces);me.update();o=bpy.data.objects.new(name,me);bpy.context.collection.objects.link(o)
 if material:me.materials.append(material)
 if uv:
  layer=me.uv_layers.new(name='UVMap')
  for loop in me.loops:layer.data[loop.index].uv=uv[loop.vertex_index]
 return o
def box(name,pos,size,material,bevel=.035,rz=0):
 bpy.ops.mesh.primitive_cube_add(size=1,location=pos);o=bpy.context.object;o.name=name;o.dimensions=size;o.rotation_euler.z=rz;bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);o.data.materials.append(material)
 if bevel:m=o.modifiers.new('Rounded crafted edges','BEVEL');m.width=bevel;m.segments=3
 return o
def ball(name,pos,scale,material,segments=24):
 bpy.ops.mesh.primitive_uv_sphere_add(segments=segments,ring_count=12,radius=1,location=pos);o=bpy.context.object;o.name=name;o.scale=scale;o.data.materials.append(material)
 for p in o.data.polygons:p.use_smooth=True
 return o
def beam(name,a,b,r,material,vertices=16):
 a,b=Vector(a),Vector(b);bpy.ops.mesh.primitive_cylinder_add(vertices=vertices,radius=r,depth=(b-a).length,location=(a+b)*.5);o=bpy.context.object;o.name=name;o.rotation_euler=(b-a).to_track_quat('Z','Y').to_euler();o.data.materials.append(material)
 for p in o.data.polygons:p.use_smooth=len(p.vertices)==4
 return o
def curve(name,points,r,material):
 cu=bpy.data.curves.new(name,'CURVE');cu.dimensions='3D';cu.bevel_depth=r;cu.bevel_resolution=2;sp=cu.splines.new('POLY');sp.points.add(len(points)-1)
 for p,v in zip(sp.points,points):p.co=(*v,1)
 o=bpy.data.objects.new(name,cu);bpy.context.collection.objects.link(o);cu.materials.append(material);return o
def bam(name,a,b,r=.085):
 a,b=Vector(a),Vector(b);o=beam(name,a,b,r,bamboo);d=b-a
 for t in np.arange(.14,d.length,.40):
  mid=a+d.normalized()*t;beam(name+' node',mid-d.normalized()*.018,mid+d.normalized()*.018,r*1.075,node_mat)
 return o
def lathe(name,pos,profile,material,segments=32):
 verts=[]
 for r,z in profile:
  for j in range(segments):a=j*TAU/segments;verts.append((pos[0]+r*math.cos(a),pos[1]+r*math.sin(a),pos[2]+z))
 faces=[(j*segments+i,j*segments+(i+1)%segments,(j+1)*segments+(i+1)%segments,(j+1)*segments+i) for j in range(len(profile)-1) for i in range(segments)]
 o=mesh(name,verts,faces,material,[(i%segments/segments,i//segments/max(1,len(profile)-1)) for i in range(len(verts))]);
 for p in o.data.polygons:p.use_smooth=True
 return o
def tea_cup(pos,scale=1):
 return lathe('Panda tea cup',pos,[(r*scale,z*scale) for r,z in [(0,0),(.11,0),(.13,.02),(.155,.16),(.142,.18),(.127,.17),(.105,.035),(0,.035)]],celadon)
def kettle(pos,scale=1,material=celadon):
 x,y,z=pos
 profile=[(0,0),(.20,.015),(.255,.075),(.29,.21),(.23,.34),(.14,.38),(.145,.40),(.12,.415),(0,.415)]
 lathe('Panda rounded tea pot',pos,[(r*scale,h*scale) for r,h in profile],material)
 ball('Panda tea lid button',(x,y,z+.46*scale),(.053*scale,.053*scale,.046*scale),material)
 curve('Panda pot spout',[(x+.19*scale,y,z+.18*scale),(x+.37*scale,y,z+.28*scale),(x+.43*scale,y,z+.38*scale)],.055*scale,material)
 curve('Panda pot arch handle',[(x+.22*math.cos(a)*scale,y,z+(.36+.30*math.sin(a))*scale) for a in np.linspace(0,math.pi,19)],.031*scale,node_mat)
def basket(pos,r=.3,h=.45):
 x,y,z=pos;lathe('Panda basket body',pos,[(0,0),(r*.8,0),(r,.08),(r,h),(r*.92,h),(r*.76,.08),(0,.08)],straw)
 for zz in np.arange(.055,h,.045):curve('Panda woven basket horizontal',[(x+(r*.85+.15*r*zz/h)*math.cos(a),y+(r*.85+.15*r*zz/h)*math.sin(a),z+zz) for a in np.linspace(0,TAU,33)],.013,straw)
 for a in np.linspace(0,TAU,18,endpoint=False):curve('Panda woven basket vertical',[(x+r*.85*math.cos(a),y+r*.85*math.sin(a),z+.02),(x+r*math.cos(a),y+r*math.sin(a),z+h)],.012,edge)
 curve('Panda basket handle',[(x+r*.72*math.cos(a),y,z+h+.25*math.sin(a)) for a in np.linspace(0,math.pi,17)],.032,straw)
def pillow(name,pos,size,material):return ball(name,pos,(size[0]/2,size[1]/2,size[2]/2),material,32)
def leaf(pos,tip,width,material=leaf_mat):
 a,b=Vector(pos),Vector(tip);d=b-a;side=d.cross(Vector((0,0,1)))
 if side.length<.01:side=Vector((1,0,0))
 side.normalize();mid=a+d*.48;top=mid+Vector((0,0,.05))
 return mesh('Panda lanceolate bamboo leaf',[tuple(a),tuple(mid+side*width),tuple(b),tuple(mid-side*width),tuple(top)],[(0,1,4),(1,2,4),(2,3,4),(3,0,4)],material)
def plant(pos,scale=1,pot=True):
 x,y,z=pos
 if pot:lathe('Panda celadon planter',pos,[(0,0),(.25,0),(.38,.1),(.4,.4),(.31,.58),(.3,.62),(.25,.62),(.25,.52)],celadon);z+=.45
 for i in range(3):
  dx=(i-1)*.18*scale;h=(1.1+i*.32)*scale;bam('Panda living bamboo',(x+dx,y,z),(x+dx+.10,y+.1,z+h),.03*scale)
  for j in range(3):
   zz=z+(.45+j*.27)*scale;sg=1 if (i+j)%2 else -1;start=(x+dx,y,zz);end=(x+dx+sg*.48*scale,y+.05,zz+.16*scale);beam('Panda bamboo twig',start,end,.011*scale,node_mat)
   for t in [.45,.8,1]:leaf(Vector(start).lerp(Vector(end),t),Vector(start).lerp(Vector(end),t)+Vector((sg*.20*scale,(-1 if j%2 else 1)*.2*scale,-.1*scale)),.07*scale,leaf_light if j%2 else leaf_mat)

def window(angle,height,radius=1):
 def pt(u,v,inset=.11):
  z=height+v;r=5.03 if z<4.65 else 5.03-(z-4.65)*1.32;a=angle+math.asin(u/r)
  r+=.075*math.sin(a*5+z*.4)+.035*math.sin(a*11-z)-inset
  return (r*math.cos(a),r*math.sin(a),z)
 verts=[pt(0,0)]+[pt(radius*math.cos(a),radius*math.sin(a)) for a in np.linspace(0,TAU,65)[:-1]]
 mesh('Panda luminous round window',verts,[(0,i+1,(i+1)%64+1) for i in range(64)],paper)
 curve('Panda round bamboo window rim',[pt(radius*math.cos(a),radius*math.sin(a),.17) for a in np.linspace(0,TAU,65)],.075,bamboo)
 # Four square-corner fretwork motifs leave the center bright and open.
 for sx in [-1,1]:
  for sz in [-1,1]:
   pts=[(.12*radius,.84*radius),(.12*radius,.64*radius),(.38*radius,.64*radius),(.38*radius,.39*radius),(.65*radius,.39*radius),(.65*radius,.13*radius),(.84*radius,.13*radius)]
   curve('Panda Chinese geometric lattice',[pt(x*sx,z*sz,.205) for x,z in pts],.022,bamboo)

def clip(poly,nx,ny,dist):
 out=[]
 for a,b in zip(poly,poly[1:]+poly[:1]):
  fa=a[0]*nx+a[1]*ny-dist;fb=b[0]*nx+b[1]*ny-dist
  if fa<=0:out.append(a)
  if (fa<0)!=(fb<0):t=fa/(fa-fb);out.append((a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])))
 return out
def extrude(name,poly,bottom,top,material):
 n=len(poly);verts=[(x,y,z) for z in [bottom,top] for x,y in poly];faces=[tuple(reversed(range(n))),tuple(range(n,2*n))]+[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
 return mesh(name,verts,faces,material,[(x/2.5,y/2.5) for x,y,z in verts])

# Continuous double-height limestone enclosure; no garden is visible through it.
seg=80;rows=[.12,.75,1.45,2.20,3.0,3.8,4.65,5.35,5.95,6.2];verts=[]
for j,z in enumerate(rows):
 for i in range(seg):
  a=i*TAU/seg;r=5.03 if z<4.65 else (5.03-(z-4.65)*1.32)
  r+=.075*math.sin(a*5+z*.4)+.035*math.sin(a*11-z)
  verts.append((r*math.cos(a),r*math.sin(a),z+(.03*math.sin(a*7+j) if j not in [0,4,9] else 0)))
faces=[]
for j in range(len(rows)-1):
 for i in range(seg):
  a=(i+.5)*TAU/seg
  if math.sin(a)<-.976 and rows[j]<2.2:continue
  k=j*seg+i;kn=j*seg+(i+1)%seg;faces.extend([(k,k+seg,kn+seg),(k,kn+seg,kn)])
faces.append(tuple(reversed(range((len(rows)-1)*seg,len(rows)*seg))))
shell=mesh('EnclosureWall',verts,faces,rock,[(math.atan2(y,x)*5/3,z/3) for x,y,z in verts])
for p in shell.data.polygons:p.use_smooth=True
for index in range(13):
 angle=(index+.2)*TAU/13;start=2.8+(index%4)*.66;length=.48+(index%3)*.24
 if math.sin(angle)<-.96:continue
 vv=[]
 for j in range(8):
  t=j/7;z=start-length*t;center_angle=angle+.035*math.sin(t*4.1+index)+t*.027
  for side in [-1,1]:
   a=center_angle+side*.0012*math.sin(math.pi*t);r=5.03 if z<4.65 else 5.03-(z-4.65)*1.32
   r+=.075*math.sin(a*5+z*.4)+.035*math.sin(a*11-z)-.09
   vv.append((r*math.cos(a),r*math.sin(a),z))
 mesh('Panda tapered natural rock fissure',vv,[(j*2,j*2+2,j*2+3,j*2+1) for j in range(7)],fissure_mat)
extrude('EnclosureFloorUnderlay',[(5.05*math.cos(a),5.05*math.sin(a)) for a in np.linspace(0,TAU,97)[:-1]],.10,.195,grout)
seeds=[(x*1.03+rng.uniform(-.25,.25),y*1.03+rng.uniform(-.25,.25)) for x in range(-5,6) for y in range(-5,6)]
boundary=[(5.02*math.cos(a),5.02*math.sin(a)) for a in np.linspace(0,TAU,97)[:-1]]
for sx,sy in seeds:
 poly=boundary[:]
 for tx,ty in seeds:
  if (sx,sy)==(tx,ty):continue
  poly=clip(poly,tx-sx,ty-sy,(tx*tx+ty*ty-sx*sx-sy*sy)*.5)
  if len(poly)<3:break
 if len(poly)<3:continue
 cx=sum(x for x,y in poly)/len(poly);cy=sum(y for x,y in poly)/len(poly);poly=[(cx+(x-cx)*.982,cy+(y-cy)*.982) for x,y in poly]
 extrude('Panda hand-cut stone floor',poly,.175,.196+rng.uniform(-.002,.002),rng.choice(stone))
window(math.pi/2,4.62,.88);window(.28,3.52,.82);window(2.87,1.75,.63)

# Rear timber sleeping loft, shaped to fit the stone perimeter.
loftpoly=[(-3.8,1.25),(2.25,1.25),(3.1,2.1),(3.1,3.65),(2.4,4.25),(-2.4,4.25),(-3.8,3.10)]
extrude('Panda loft structural platform',loftpoly,2.76,2.99,wood)
for i in range(22):
 x=-3.75+i*.315;poly=clip(loftpoly,-1,0,-x);poly=clip(poly,1,0,x+.30)
 if len(poly)>2:extrude('Panda individual loft board',poly,2.985,3.015,edge if i%5==0 else wood)
for x in [-3.5,1.8]:
 bam('Panda loft bamboo support',(x,1.42,.19),(x,1.42,2.83),.14)
 beam('Panda loft diagonal bracket',(x,1.42,2.24),(x+(.46 if x<0 else -.46),1.42,2.82),.08,wood)
box('Panda loft front beam',(-.76,1.26,2.85),(6.14,.24,.30),wood)
# Walkable right hand stairs: 14 treads from floor to loft, width 1.18.
steps=[]
for i in range(14):
 y=-2.50+i*.295;top=.196+(i+1)*(3.015-.196)/14
 box('Panda stair tread %02d'%i,(3.14,y,top-.08),(1.2,.325,.16),edge,.025)
 steps.append({'name':'stair_%02d'%i,'center':[3.14,top-.08,-y],'size':[1.2,.16,.325]})
beam('Panda stair left stringer',(2.62,-2.63,.28),(2.62,1.40,2.95),.105,wood)
beam('Panda stair right stringer',(3.66,-2.63,.28),(3.66,1.40,2.95),.105,wood)
for i in range(0,14,3):
 y=-2.50+i*.295;top=.196+(i+1)*(3.015-.196)/14
 bam('Panda stair newel',(2.56,y,top),(2.56,y,top+.70),.048)
bam('Panda stair sloping rail',(2.56,-2.58,1.03),(2.56,1.42,3.75),.065)
for x in [-3.55,-2.45,-1.35,-.25,.85,1.95]:bam('Panda loft balustrade',(x,1.25,3.01),(x,1.25,3.56),.038)
bam('Panda loft low top rail',(-3.60,1.25,3.56),(2.0,1.25,3.56),.045)

# Bamboo bed and ochre quilt, sized for a small animal rather than a human hall.
bed=(-1.85,2.75)
for x in [-2.93,-.76]:
 for y in [2.04,3.58]:bam('Panda bamboo bed leg',(x,y,3.02),(x,y,3.70 if y>3 else 3.54),.072)
for y in [2.04,3.58]:bam('Panda bamboo bed frame',(-2.98,y,3.34),(-.71,y,3.34),.075)
for x in [-2.93,-.76]:bam('Panda bamboo bed side',(x,2.0,3.34),(x,3.62,3.34),.070)
box('Panda sleeping mattress',(-1.85,2.79,3.49),(2.17,1.50,.23),cream,.105)
box('Panda ochre quilt',(-1.85,2.58,3.63),(2.14,1.04,.17),gold,.075)
pillow('Panda pillow',(-1.88,3.32,3.65),(1.35,.38,.24),cream)
bam('Panda bamboo head rail',(-2.93,3.60,3.99),(-.76,3.60,3.99),.073)
for x in np.arange(-2.80,-.77,.25):bam('Panda bamboo head slat',(x,3.60,3.46),(x,3.60,3.94),.030)
# Loft reading desk, stacked books, writing brush and celadon flower vase.
box('Panda loft desk top',(.65,3.50,3.56),(1.5,.72,.14),edge)
for x in [.07,1.23]:
 for y in [3.25,3.73]:bam('Panda loft desk leg',(x,y,3.02),(x,y,3.52),.060)
for i,(dx,w) in enumerate([(-.38,.46),(-.35,.50),(-.31,.42)]):box('Panda bound travel notebook',(.65+dx,3.45,3.66+i*.045),(w,.28,.045),green if i%2 else cream,.012,rz=(i-1)*.06)
lathe('Panda brush holder',(1.10,3.54,3.64),[(0,0),(.10,0),(.10,.19),(.085,.20),(.08,.02),(0,.02)],bamboo)
for i in range(3):beam('Panda writing brush',(1.10+i*.025,3.54,3.71),(1.03+i*.09,3.54,4.02+i*.025),.013,wood)
pillow('Panda loft woven stool',(.68,2.76,3.12),(.65,.58,.19),straw)

# Large woven tea rug, bamboo tea table and two low floor cushions.
box('Panda tea woven rug',(0,-.23,.216),(3.15,2.80,.035),straw,.05)
for y in [-1.60,1.13]:
 for x in np.arange(-1.45,1.50,.09):beam('Panda rug woven fringe',(x,y,.221),(x,y+(-.14 if y<0 else .14),.22),.014,straw,8)
for x in [-.76,.76]:
 for y in [-.49,.49]:bam('Panda tea table leg',(x,y,.235),(x,y,.67),.077)
for i in range(6):box('Panda tea table bamboo slat',(0,-.46+i*.185,.73),(1.83,.175,.13),edge,.035)
for y in [-.55,.55]:bam('Panda tea table rim',(-.9,y,.735),(.9,y,.735),.065)
box('Panda tea table sage runner',(.30,0,.806),(.48,1.14,.018),green,.01)
box('Panda tea tray',(-.34,-.05,.824),(.71,.43,.05),wood,.026)
kettle((.30,.20,.815),.66)
tea_cup((-.52,-.05,.855),.67);tea_cup((-.21,-.11,.855),.67)
lathe('Panda little flower bottle',(.66,-.22,.82),[(0,0),(.085,0),(.12,.1),(.08,.19),(.035,.24),(.035,.31),(.025,.31),(.025,.25)],celadon)
for i in range(4):
 end=(.60+.12*math.sin(i*2),-.22+.12*math.cos(i*2),1.39+i*.04);beam('Panda tea flowers',(.66,-.22,1.1),end,.006,node_mat)
 for a in np.linspace(0,TAU,6)[:-1]:ball('Panda ivory blossom',(end[0]+.025*math.cos(a),end[1]+.025*math.sin(a),end[2]),(.034,.018,.027),cream,12)
pillow('Panda visitor cushion',(0,-1.17,.305),(.84,.79,.21),straw)
pillow('Panda host cushion',(-1.26,.18,.29),(.81,.76,.18),green)

# Left tea cabinet and back open pantry, with actual containers on each shelf.
box('Panda low tea cabinet',(-3.6,.1,.67),(.85,2.0,.91),wood)
box('Panda low tea cabinet top',(-3.6,.1,1.19),(.99,2.12,.13),edge)
for y in [-.55,.05,.65]:
 box('Panda cabinet reed inset',(-3.15,y,.73),(.045,.49,.69),green,.02)
 bam('Panda cabinet door handle',(-3.09,y-.10,.89),(-3.09,y+.10,.89),.022)
kettle((-3.56,.56,1.27),.80,teapot_mat)
tea_cup((-3.36,-.05,1.265),.70);basket((-3.51,-.60,1.26),.20,.22)
for x in [-1.95,.9]:
 box('Panda rear pantry side',(x,3.65,1.39),(.13,.58,2.36),wood)
for z in [.30,1.03,1.75,2.50]:box('Panda rear pantry shelf',(-.52,3.65,z),(2.98,.69,.11),edge)
for z in [.37,1.10,1.82]:
 for x in [-1.48,-.79,-.10,.57]:
  if rng.random()<.45:basket((x,3.60,z),.23,.38)
  else:lathe('Panda stored tea jar',(x,3.62,z),[(0,0),(.19,0),(.25,.12),(.23,.33),(.14,.43),(.14,.46),(0,.46)],celadon if rng.random()<.7 else teapot_mat)
basket((1.57,2.17,.20),.29,.53)
# Linen scroll with genuinely modelled abstract mountains, no generated image plane.
box('Panda ink scroll linen',(-3.20,2.72,1.94),(1.03,.035,1.48),cream,.008)
for z in [1.18,2.70]:bam('Panda scroll wooden roller',(-3.79,2.68,z),(-2.61,2.68,z),.034)
curve('Panda scroll hanging cord',[(-3.68,2.71,2.70),(-3.20,2.72,2.95),(-2.72,2.71,2.70)],.008,node_mat)
for i in range(3):
 base=1.34+i*.21;peaks=[(-3.64,base),(-3.52,base+.10),(-3.40,base+.24),(-3.29,base+.39-i*.04),(-3.16,base+.13),(-3.00,base+.31),(-2.78,base+.08)]
 verts=[(x,2.691-i*.001,z) for x,z in peaks]+[(-2.78,2.691-i*.001,base),(-3.64,2.691-i*.001,base)]
 mesh('Panda ink mountain silhouette',verts,[tuple(range(len(verts)))],ink_light if i<2 else ink)
plant((-4.04,-1.96,.196),.92);plant((4.1,.98,.196),.70)
plant((1.83,3.35,3.015),.39)

def lantern(pos,scale=1):
 x,y,z=pos;ball('Panda glowing paper lantern',(x,y,z+.26*scale),(.18*scale,.18*scale,.25*scale),lamp_mat)
 for zz in [.03,.48]:lathe('Panda lantern cap',(x,y,z+zz*scale),[(0,0),(.205*scale,0),(.205*scale,.055*scale),(0,.055*scale)],wood)
 for a in np.linspace(0,TAU,9)[:-1]:beam('Panda lantern bamboo rib',(x+.18*scale*math.cos(a),y+.18*scale*math.sin(a),z+.06*scale),(x+.18*scale*math.cos(a),y+.18*scale*math.sin(a),z+.49*scale),.013*scale,bamboo)
 curve('Panda lantern loop',[(x+.11*scale*math.cos(a),y,z+(.54+.12*math.sin(a))*scale) for a in np.linspace(0,math.pi,13)],.019*scale,wood)
lantern((-3.42,-.58,1.29),.76)
lantern((1.15,3.57,1.83),.65)
# The front inner door is closed artwork; engine portal triggers before it.
for x in [-.52,.52]:box('Panda room side door',(x,-4.74,1.15),(1.015,.14,1.92),wood,.035)
for x in [-1.12,1.12]:bam('Panda round door jamb',(x,-4.66,.19),(x,-4.66,2.16),.12)
beam('Panda inner door lintel',(-1.14,-4.66,2.18),(1.14,-4.66,2.18),.15,wood)
for x in [-.13,.13]:curve('Panda inner door pull',[(x+.065*math.cos(a),-4.63,1.12+.10*math.sin(a)) for a in np.linspace(0,TAU,25)],.018,bamboo)

# Detail work remains real scene geometry and standard exported PBR maps.
exec((ROOT/'tools/panda-house-detail.py').read_text(),globals())

def area(name,pos,target,power,size,color):
 bpy.ops.object.light_add(type='AREA',location=pos);o=bpy.context.object;o.name=name;o.data.energy=power;o.data.shape='DISK';o.data.size=size;o.data.color=color;o.rotation_euler=(Vector(target)-o.location).to_track_quat('-Z','Y').to_euler();return o
def render_setup():
 s=bpy.context.scene;s.render.engine='CYCLES';s.cycles.samples=40;s.cycles.use_denoising=True;s.render.resolution_x=1200;s.render.resolution_y=1000;s.render.resolution_percentage=100;s.world.color=(.16,.17,.19)
 s.view_settings.view_transform='AgX';s.view_settings.look='AgX - Medium High Contrast';s.view_settings.exposure=-.1
def camera(name,pos,target,lens=24):
 bpy.ops.object.camera_add(location=pos);c=bpy.context.object;c.name=name;c.data.lens=lens;c.data.clip_start=.04;c.rotation_euler=(Vector(target)-c.location).to_track_quat('-Z','Y').to_euler();return c
main_camera=camera('Panda room main camera',(.35,-4.42,4.05),(0,.80,2.00),20)
side_camera=camera('Panda room side camera',(-3.34,-3.25,2.30),(.45,1.18,1.86),23)
loft_camera=camera('Panda room loft camera',(2.10,0,5.10),(-1.0,2.60,3.65),27)
close_camera=camera('Panda tea craft close camera',(-2.30,-2.95,1.63),(-.05,0,.78),44)
stone_camera=camera('Panda natural stone close camera',(-2.8,-.9,2.20),(-4.5,.40,1.58),44)
area('Panda daylight rear',(0,4.1,4.8),(-.6,-.6,1),560,2.4,(1,.83,.62))
area('Panda daylight right',(4.3,.4,3.5),(0,0,1),480,2.0,(1,.84,.65))
area('Panda room fill',(-1.1,-3.0,4.2),(0,1,1.2),310,4.0,(.78,.86,1))
area('Panda loft soft light',(-1.6,2.5,5.5),(-1.4,2.7,3.0),160,2.0,(1,.88,.70))
render_setup()
bpy.context.scene.camera=main_camera
bpy.ops.wm.save_as_mainfile(filepath=str(NATIVE/'panda-home.blend'))

def export_runtime(path,prefix):
 # Keep editable source separated; batch runtime by material after saving.
 for o in list(bpy.context.scene.objects):
  if o.type in ['CURVE','MESH']:
   bpy.ops.object.select_all(action='DESELECT');o.select_set(True);bpy.context.view_layer.objects.active=o
   bpy.ops.object.convert(target='MESH')
   if not o.data.uv_layers:make_uv_world(o,.20 if any(word in o.name for word in ['strand','coil','fringe','woven basket']) else 1.6)
 walls=[o for o in bpy.context.scene.objects if o.name=='EnclosureWall' or o.name.startswith('Panda hewn rock face')]
 if len(walls)>1:
  bpy.ops.object.select_all(action='DESELECT')
  for o in walls:o.select_set(True)
  bpy.context.view_layer.objects.active=next(o for o in walls if o.name=='EnclosureWall');bpy.ops.object.join();bpy.context.object.name='EnclosureWall'
 groups={}
 for o in list(bpy.context.scene.objects):
  if o.type=='MESH' and not o.name.startswith('Enclosure'):groups.setdefault(o.data.materials[0].name if o.data.materials else 'none',[]).append(o)
 for i,objects in enumerate(groups.values()):
  group_material=objects[0].data.materials[0].name if objects[0].data.materials else ''
  bpy.ops.object.select_all(action='DESELECT')
  for o in objects:o.select_set(True)
  bpy.context.view_layer.objects.active=objects[0];bpy.ops.object.join();bpy.context.object.name='PandaWindowBackground' if group_material=='Panda softly diffused garden daylight' else prefix+'_'+str(i).zfill(2)
 bpy.ops.export_scene.gltf(filepath=str(path),export_format='GLB',export_apply=True,export_animations=False,export_cameras=False,export_lights=False)
 return {'mesh_batches':sum(o.type=='MESH' for o in bpy.context.scene.objects),'triangles':sum(sum(len(p.vertices)-2 for p in o.data.polygons) for o in bpy.context.scene.objects if o.type=='MESH'),'bytes':path.stat().st_size}
home_stats=export_runtime(ASSETS/'panda-home.glb','PandaHome')

if '--interior-only' not in sys.argv:
 # Exterior is a separate compact stone cottage with a bamboo eave and porch.
 bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
 seg=64;rows=[(3.58,.08),(3.66,1.2),(3.58,2.5),(3.12,3.65),(2.24,4.50),(.02,4.95)];v=[]
 for row,(r,z) in enumerate(rows):
  for i in range(seg):a=i*TAU/seg;rr=r+.09*math.sin(a*5+row*.8);v.append((rr*math.cos(a),rr*math.sin(a),z))
 faces=[]
 for j in range(len(rows)-1):
  for i in range(seg):
   a=(i+.5)*TAU/seg
   if math.sin(a)<-.943 and j<2:continue
   k=j*seg+i;n=j*seg+(i+1)%seg;faces.append((k,n,n+seg,k+seg))
 ext=mesh('Panda exterior solid stone shell',v,faces,rock,[(math.atan2(y,x)*3,z/2) for x,y,z in v]);
 for p in ext.data.polygons:p.use_smooth=True
 for x in [-.51,.51]:box('Panda bamboo front door',(x,-3.51,1.20),(1,.14,2.15),wood)
 for x in [-1.10,1.10]:bam('Panda cottage door jamb',(x,-3.61,.05),(x,-3.61,2.36),.13)
 beam('Panda cottage door header',(-1.14,-3.61,2.37),(1.14,-3.61,2.37),.17,wood)
 for x in [-.14,.14]:curve('Panda cottage door brass ring',[(x+.065*math.cos(a),-3.61,1.19+.085*math.sin(a)) for a in np.linspace(0,TAU,25)],.017,bamboo)
 # Small green tiled bamboo porch roof: real thick curved strips.
 for i in range(13):
  x=-1.42+i*.237;poly=[(x,-3.24,2.69),(x+.225,-3.24,2.69),(x+.225,-4.27,2.53),(x,-4.27,2.53)]
  o=mesh('Panda porch overlapping green tile',poly,[(0,1,2,3)],green);so=o.modifiers.new('Solid roof tile','SOLIDIFY');so.thickness=.055
 for x in [-1.43,1.43]:bam('Panda porch upright',(x,-4.02,.1),(x,-4.02,2.48),.078)
 beam('Panda porch front beam',(-1.54,-4.18,2.45),(1.54,-4.18,2.45),.10,wood)
 box('Panda cottage porch threshold',(0,-3.92,.09),(2.65,1.05,.17),stone[2])
 for i in range(4):ball('Panda approach flagstone',((-.12 if i%2 else .15),-4.8-i*.65,.04),(.57,.41,.075),stone[i%4],16)
 # Front upper round window centered over entry.
 def exterior_window_pt(x,dz,offset=.09):
  z=3.55+dz
  for j in range(len(rows)-1):
   r0,z0=rows[j];r1,z1=rows[j+1]
   if z0<=z<=z1:
    t=(z-z0)/(z1-z0);r=r0+(r1-r0)*t;a=-math.pi/2+math.asin(x/r);r+=.09*math.sin(a*5+(j+t)*.8);break
  return (x,-math.sqrt(r*r-x*x)-offset,z)
 r=.64;mesh('Panda exterior luminous round window',[exterior_window_pt(0,0)]+[exterior_window_pt(r*math.cos(a),r*math.sin(a)) for a in np.linspace(0,TAU,49)[:-1]],[(0,i+1,(i+1)%48+1) for i in range(48)],paper)
 curve('Panda exterior round window rim',[exterior_window_pt(r*math.cos(a),r*math.sin(a),.16) for a in np.linspace(0,TAU,49)],.075,bamboo)
 for x in [-.2,.2]:curve('Panda exterior window fret',[exterior_window_pt(x,z,.18) for z in np.linspace(-.48,.51,12)],.026,bamboo)
 curve('Panda exterior window crossbar',[exterior_window_pt(x,0,.18) for x in np.linspace(-.59,.59,12)],.027,bamboo)
 plant((-2.6,-2.9,.07),1.35,False);plant((2.9,-2.1,.07),1.1,False);plant((-3.0,.4,.07),1.45,False)
 lantern((1.13,-3.79,1.75),.58)
 # The sign uses carved bamboo leaf emblem rather than tiny unreadable lettering.
 beam('Panda cottage sign post',(-2,-4.34,.05),(-2,-4.34,1.34),.065,wood)
 box('Panda cottage sign plaque',(-2,-4.36,1.12),(.66,.075,.46),bamboo,.045)
 beam('Panda carved sign stalk',(-2.15,-4.41,.99),(-1.87,-4.41,1.28),.014,green)
 for x,z,sg in [(-2.10,1.08,-1),(-2.01,1.16,1),(-1.95,1.23,-1)]:mesh('Panda carved sign bamboo leaf',[(x,-4.415,z),(x+sg*.14,-4.415,z+.03),(x+sg*.06,-4.415,z+.09)],[(0,1,2)],green)
 render_setup();excam=camera('Panda cottage exterior camera',(7.7,-11.3,6.1),(0,-.4,2),42);bpy.context.scene.camera=excam
 area('Panda exterior soft sunlight',(-4,-6,10),(0,0,0),1800,7,(1,.87,.69));area('Panda exterior sky fill',(4,2,7),(0,0,1.5),800,6,(.71,.83,1))
 bpy.ops.wm.save_as_mainfile(filepath=str(NATIVE/'panda-exterior.blend'))
 bpy.context.scene.render.filepath=str(EVIDENCE/'panda-exterior-blender.png');bpy.ops.render.render(write_still=True)
 exterior_stats=export_runtime(ASSETS/'panda-exterior.glb','PandaExterior')

else:
 exterior_stats=json.loads((ASSETS/'panda-home.json').read_text())['runtime']['exterior']

# Explicit local Godot-space collision/nav contract for game integration.
colliders=[{'name':'floor','center':[0,.08,0],'size':[10.1,.22,10.1]},
 {'name':'loft','center':[-.34,2.90,-2.69],'size':[6.84,.23,2.93]},
 {'name':'tea_table','center':[0,.56,0],'size':[1.90,.72,1.13]},
 {'name':'left_cabinet','center':[-3.6,.69,-.1],'size':[.91,1.0,2.06]},
 {'name':'rear_pantry','center':[-.52,1.35,-3.65],'size':[3.06,2.40,.75]},
 {'name':'bed','center':[-1.85,3.47,-2.79],'size':[2.30,.85,1.67]},
 {'name':'loft_desk','center':[.65,3.32,-3.50],'size':[1.58,.61,.80]}]+steps
for i in range(40):
 a=(i+.5)*TAU/40
 if math.sin(a)<-.976:continue
 colliders.append({'name':'wall_%02d'%i,'center':[5.06*math.cos(a),3.14,-5.06*math.sin(a)],'size':[.80,6.2,.30],'rotation_y':a-math.pi/2})
for x in [-3.5,1.8]:colliders.append({'name':'loft_support','center':[x,1.5,-1.42],'size':[.32,2.65,.32]})
meta={'version':1,'authoring':'Blender geometry; local Godot Y-up coordinates','interior_radius':5.0,'floor_y':.20,'loft_y':3.015,'roof_y':6.2,'entry_spawn':[0,.22,3.85],'entry_facing':[0,0,-1],'exit_bounds':{'x':[-1.0,1.0],'z_min':4.36},'door_local':[0,1.2,4.75],'main_camera':{'position':[.35,4.05,4.42],'target':[0,2.00,-.80],'fov':74},'side_camera':{'position':[-3.34,2.30,3.25],'target':[.45,1.86,-1.18],'fov':68},'camera_bounds':{'radius':4.55,'y':[.75,5.6]},'panda_position':[-1.35,.20,-.25],'panda_yaw':math.pi/2,'tea_position':[0,.2,1.15],'tea_table_position':[0,.2,0],'loft_position':[0,3.035,-2.2],'stair_route':[[3.14,.22,2.89]]+[[3.14,.196+(i+1)*(3.015-.196)/14+.025,2.50-i*.295] for i in range(14)]+[[2.80,3.04,-1.5],[1.40,3.04,-1.85]],'colliders':colliders,'exterior':{'radius':3.7,'door':[0,.15,4.35],'spawn_outside':[0,.25,5.05],'porch':[0,.15,3.9],'approach_length':7.0,'colliders':[{'name':'exterior_shell','type':'cylinder','center':[0,2.0,0],'radius':3.53,'height':4.0}]},'runtime':{'home':home_stats,'exterior':exterior_stats},'review':'Authentic Blender geometry. AI reference is design guidance, not a background plane. Panda imported independently from Tripo.'}
meta.update({'exit_z':4.36,'camera_views':{'main':meta['main_camera'],'side':meta['side_camera'],'loft':{'position':[2.10,5.10,0],'target':[-1.0,3.65,-2.60],'fov':60}},'camera_main':meta['main_camera'],'tea_guest_position':[0,.22,1.17],
 'furniture_collisions':[{'name':c['name'],'position':c['center'],'size':c['size'],'yaw':c.get('rotation_y',0)} for c in colliders if not c['name'].startswith('wall_') and c['name']!='floor'],
 'qa_ground_route':[[0,.22,3.85],[0,.22,1.65],[0,.22,1.17],[1.5,.22,1.65],[2.25,.22,2.95],[3.14,.22,2.89]],
 'qa_loft_route':[[2.80,3.04,-1.5],[1.40,3.04,-1.85],[-.18,3.04,-1.77]],
 'qa_wall_start':[-1.50,.22,2.6],'qa_wall_direction':[-1,0,0],'qa_wall_route':[[0,.22,3.85],[-1.50,.22,2.6]],
 'room_bounds':{'min':[-5.1,.10,-5.1],'max':[5.1,6.22,5.1]}})
meta['windows']=[{'name':name,'position':[4.76*math.cos(a),z,-4.76*math.sin(a)],'inward_normal':[-math.cos(a),0,math.sin(a)],'width':r*2,'height':r*2} for name,a,z,r in [('rear_loft',math.pi/2,4.62,.88),('right_stairs',.28,3.52,.82),('left_tea',2.87,1.75,.63)]]
meta['lamps']=[{'name':'tea_cabinet_lantern','position':[-3.42,1.49,.58],'color':'ffd49a','energy':.28,'range':2.6},{'name':'pantry_lantern','position':[1.15,2.0,-3.57],'color':'ffd49a','energy':.20,'range':2.2}]
meta['detail_revision']=21
(ASSETS/'panda-home.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2))
print('PANDA_HOME_COMPLETE',json.dumps({'home':home_stats,'exterior':exterior_stats}),flush=True)

if os.environ.get('XLANDS_SKIP_REVIEW')=='1':raise SystemExit(0)

# Multi-angle evidence from the SAME editable scene, adding the actual Tripo panda.
if (ASSETS/'panda.glb').exists():
 bpy.ops.wm.open_mainfile(filepath=str(NATIVE/'panda-home.blend'))
 before=set(bpy.data.objects);bpy.ops.import_scene.gltf(filepath=str(ASSETS/'panda.glb'));new=set(bpy.data.objects)-before
 roots=[o for o in new if o.parent not in new]
 for o in roots:o.location+=Vector((-1.35,.25,.20));o.rotation_euler.z=math.pi/2
 bpy.ops.wm.save_as_mainfile(filepath=str(NATIVE/'panda-home-with-tripo.blend'))
 for name,out in [('Panda room main camera','panda-room-main-blender.png'),('Panda room side camera','panda-room-side-blender.png'),('Panda room loft camera','panda-room-loft-blender.png'),('Panda tea craft close camera','panda-tea-detail-blender.png'),('Panda natural stone close camera','panda-stone-detail-blender.png')]:
  bpy.context.scene.camera=bpy.data.objects[name];bpy.context.scene.render.filepath=str(EVIDENCE/out);bpy.ops.render.render(write_still=True)
