#!/usr/bin/env python3
"""Export an installed native world with Godot 4.7.2 and package verified chunks."""
from pathlib import Path
import argparse,gzip,hashlib,json,re,subprocess

parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('world',choices=['frog','conan'])
parser.add_argument('output',type=Path,help='Dedicated output directory for this world')
parser.add_argument('--godot',default='godot',help='Godot 4.7.2 executable')
args=parser.parse_args()
root=Path(__file__).resolve().parents[1]
project=root/'worlds'/args.world/('source' if args.world=='frog' else 'web-project')
if not (project/'ui-font.otf').exists():
 raise SystemExit('Install assets first: tools/fetch-native-assets.py '+('frog' if args.world=='frog' else 'conan-web'))
output=args.output.resolve();output.mkdir(parents=True,exist_ok=True)
subprocess.run([args.godot,'--headless','--path',str(project),'--editor','--import'],check=True)
subprocess.run([args.godot,'--headless','--path',str(project),'--export-release','Web',str(output/'index.html')],check=True)
html=(output/'index.html').read_text()
match=re.search(r'const GODOT_CONFIG = (\{.*?\});',html)
if not match:raise SystemExit('Unsupported Godot export shell; generated files were preserved.')
config=json.loads(match.group(1));source=output/'index.pck';raw=source.read_bytes();chunks=[]
for i,start in enumerate(range(0,len(raw),16*1024*1024)):
 data=raw[start:start+16*1024*1024]
 encoded=gzip.compress(data,compresslevel=8,mtime=0)
 name=f'world-{i:03}.bin.gz';(output/name).write_bytes(encoded)
 chunks.append(dict(file=name,offset=start,rawBytes=len(data),bytes=len(encoded),sha256=hashlib.sha256(data).hexdigest()))
for stale in output.glob('world-*.bin.gz'):
 if stale.name not in {c['file'] for c in chunks}:stale.unlink()
(output/'world-pack.json').write_text(json.dumps(dict(totalBytes=len(raw),sha256=hashlib.sha256(raw).hexdigest(),chunks=chunks),indent=2)+'\n')
shell=(root/'tools/native-world-shell.html').read_text()
shell=shell.replace('CONFIG_JSON',json.dumps(config)).replace('JUMP_BUTTON','<button data-action="jump" aria-label="Jump">↑</button>' if args.world=='frog' else '')
(output/'index.html').write_text(shell)
# This pack was generated by the export above; the checked source project remains intact.
source.unlink()
(output/'OFL.txt').write_bytes((project/'OFL.txt').read_bytes())
(output/'FONT-SOURCE.md').write_bytes((project/'FONT-SOURCE.md').read_bytes())
print(json.dumps(dict(world=args.world,directory=str(output),downloadBytes=sum(c['bytes'] for c in chunks),chunks=len(chunks))))
